sudo: false

stages:
  - lint
  - test
  - name: push-docker-image
    if: branch = master

node_js_defaults: &node_js_defaults
  language: node_js
  node_js: "10"
  cache:
    yarn: true
    directories:
      - node_modules

docker_defaults: &docker_defaults
  sudo: required
  language: generic
  services:
    - docker

jobs:
  include:
    - stage: lint
      <<: *node_js_defaults
      script: ./scripts/ci/lint.sh

    - stage: test
      <<: *node_js_defaults
      script: ./scripts/ci/test.sh

    - stage: push-docker-image
      <<: *docker_defaults
      script: ./scripts/ci/push_docker_image.sh
