[build]
# The directory to look for package.json, .nvmrc, etc.
base = ""
# Build output directory.
publish = "dist"
# Command to build the files.
command = "yarn build:prod"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
