[build]
  # The directory to look for package.json, .nvmrc, etc.
  base = ""
  # Build output directory.
  publish = "dist"
  # Command to build the files.
  command = "yarn build:prod"

  environment = { ENABLE_ANALYTICS = "true", ENABLE_ERROR_TRACKING = "true", SENTRY_DSN = 'https://4e2327c6719a41edab217142272e5a79@sentry.io/1245908' }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.develop]
  environment = { ENABLE_ANALYTICS = "false", ENABLE_ERROR_TRACKING = "false" }
