version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10@sha256:7f69837d308dc50f32c8ccd3139483c3fecc71ff4500119d57167b3adc518442
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test:unit
